Grid Templates
att-cloudnative-labs/swarmhub pull request #14
Opened 2020-02-07 05:15 UTC by gdomanguera

**Grid Templates Specifications:**
•	A template is used to define a grid configuration.
•	This template will contain all the configuration that we currently do for a Grid.
•	The user can add/modify/delete a Grid Template
•	The user can create a Grid from a Grid Template
•	When we create a test, we create it from the Grid as we currently do.

**Sample use case:**  
•	Run a test every 2 weeks that are identical.  User can select the same Grid Template and create a grid from that each time they run this test.

**Note:**
•	This will require a new table in cockroachdb `grid_template` which is added in the `tables.txt` script

2020-02-07 17:12 UTC, kmhagan requested changes
Looks good! If you could make the small variable name changes I put in the comments I think this is ready to be merged

2020-02-07 17:12 UTC, kmhagan commented on services/swarmhub/src/swarmhub/api/gridtemplate.go
> +	json, err := json.Marshal(gridTemplate)
Can you rename the Marshal response from "json" to "b" or "jsonData"? Shadowing the json package could lead to confusion down the line

2020-02-07 17:12 UTC, kmhagan commented on services/swarmhub/src/swarmhub/api/gridtemplate.go
> +	json, err := json.Marshal(gridTemplates)
same here

2020-02-07 17:12 UTC, kmhagan commented on services/swarmhub/src/swarmhub/api/gridtemplate.go
> +	json, err := json.Marshal(gridTemplate)
and here

2020-02-10 03:00 UTC, gdomanguera commented
@kmhagan variable updated and renamed to `jsonData`

2020-02-10 16:32 UTC, merged